// FORK: the upstream barrel also re-exported four sibling modules that this fork
// does not port yet, and they are omitted here rather than stubbed:
//
//   ./compartment-storage.js    C group (Step 20) — pulls the embedding providers
//   ./message-index.js          C group (Step 20) — same
//   ./project-docs-hash.js      Batch 2 (Step 31)
//   ./project-identity.js       Batch 2 (Step 31)
//
// Each is restored at the step that ports it. Nothing in the A group imports
// them, so the barrel stays self-consistent meanwhile.
export {
    clearCompressionDepth,
    getAverageCompressionDepth,
    getMaxCompressionDepth,
    incrementCompressionDepth,
} from "./compression-depth-storage.js";
export { ensureContextStoreUuid, getContextStoreUuid } from "./context-store-uuid.js";
export { runMigrations } from "./migrations.js";
export {
    type CloneCompartmentRow,
    type CloneSessionStateFilter,
    type CloneTagRow,
    type CopySessionStateForCloneResult,
    copySessionStateForClone,
} from "./storage-clone.js";
export {
    applySqliteTuningPragmas,
    type ContextDatabase,
    closeDatabase,
    enforceSchemaFence,
    FORK_MIGRATION_VERSION_FLOOR,
    getDatabasePath,
    getDatabasePersistenceError,
    getPersistedSchemaVersion,
    initializeDatabase,
    isDatabasePersisted,
    LATEST_SUPPORTED_VERSION,
    type OpenDatabaseOptions,
    openDatabase,
    runSqliteOptimize,
    schemaVersionIsSupported,
    setSqlitePragmaConfig,
} from "./storage-db.js";
export {
    beginSynapseBatchLedger,
    type EmbeddingMeasurementInput,
    type EmbeddingMeasurementRow,
    finishSynapseBatchLedger,
    listEmbeddingMeasurements,
    normalizedQueryHash,
    recordEmbeddingMeasurement,
    type SynapseBatchLedgerInput,
} from "./storage-embedding-measurements.js";
export {
    deleteIdentityRekeyMap,
    getIdentityRekeyMap,
    type IdentityRekeyMapRow,
    listIdentityRekeyMaps,
    upsertIdentityRekeyMap,
} from "./storage-identity-rekey-map.js";
export {
    clearM0MutationsForSession,
    deleteM0Mutation,
    getM0Mutation,
    getM0MutationsAfterId,
    getM0MutationsBySession,
    getMaxM0MutationId,
    type M0MutationLogRow,
    type M0MutationType,
    queueM0Mutation,
    queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log.js";
export {
    getMaxMemoryMutationId,
    getMaxMemoryMutationIdForProjects,
    getMemoryMutation,
    getMemoryMutationsForRender,
    getMemoryMutationsForRenderByProjects,
    MEMORY_VISIBILITY_MUTATION_CATEGORY,
    type MemoryMutationLogRow,
    type MemoryMutationType,
    queueMemoryMutation,
} from "./storage-memory-mutation-log.js";
export {
    type AcquireWrapupResult,
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    acquireWrapupInProgress,
    addProcessedImageStrippedIds,
    addStaleReduceStrippedIds,
    advanceToolReclaimWatermark,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    applyStrippedPlaceholderDelta,
    armThinkingBindingRecovery,
    type Channel2NudgeState,
    captureChannel1PostReduceGraceBaseline,
    casChannel2NudgeClaim,
    casChannel2NudgeState,
    claimChannel2NudgeState,
    clearCachedM0,
    clearCachedM0M1,
    clearDetectedContextLimit,
    clearEmergencyDrainLatch,
    clearEmergencyRecovery,
    clearHistorianDrainFailure,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedReasoningWatermark,
    clearPersistedTodoSyntheticAnchor,
    clearSession,
    clearThinkingBindingRecoveryIf,
    DRAIN_WINDOW_MS,
    deliverNoteNudgeAtomic,
    describeProtectedTailDrainBudgetSkip,
    getAutoSearchHintDecisions,
    getChannel1NudgeState,
    getChannel2NudgeClaim,
    getChannel2NudgeClaimedAt,
    getChannel2NudgeState,
    getHiddenSeamPlaceholderIds,
    getHistorianFailureState,
    getLastNudgeUndropped,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOrCreateSessionMeta,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedReasoningWatermark,
    getPersistedTodoPermissionDenied,
    getPersistedTodoSyntheticAnchor,
    getProcessedImageStrippedIds,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getSessionWorkMetrics,
    getStaleReduceStrippedIds,
    getStrippedPlaceholderIds,
    getThinkingBindingRecoveryTarget,
    getWrapupInProgressState,
    incrementHistorianFailure,
    isWrapupInProgress,
    loadPersistedUsage,
    loadProtectedTailMeta,
    MAX_STRIPPED_PLACEHOLDER_IDS,
    markChannel1PostReduceGracePending,
    markProtectedTailPolicyV3Seeded,
    markSessionCleanupPending,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistCachedM0Payload,
    type PersistedChannel1NudgeLevel,
    type PersistedChannel1NudgeState,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    type PersistedUsageState,
    type ProtectedTailDrainBudgetState,
    type ProtectedTailDrainReservation,
    type ProtectedTailDrainReserveResult,
    type ProtectedTailMeta,
    type ProtectedTailSeedResult,
    persistCachedM0,
    protectedTailWindowBudget,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordHistorianDrainFailure,
    recordOverflowDetected,
    recordProtectedTailNoEligibleHead,
    recordProtectedTailPublicationFloor,
    releaseWrapupInProgress,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    replacePendingCompactionMarkerStateIf,
    reserveProtectedTailDrainTokens,
    resetLastNudgeCycle,
    resetLastNudgeCycleIfTailShrank,
    resetProtectedTailNoEligibleHead,
    retryPendingRustSessionCleanupsForProject,
    retryPendingSessionCleanups,
    rollbackProtectedTailDrainReservation,
    setChannel1NudgeState,
    setChannel2NudgeState,
    setLastNudgeUndropped,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedReasoningWatermark,
    setPersistedTodoPermissionDenied,
    setPersistedTodoSyntheticAnchor,
    setSessionWorkMetrics,
    setStrippedPlaceholderIds,
    THINKING_BINDING_RECOVERY_ALL_ASSISTANTS,
    updateSessionMeta,
    updateWrapupInProgress,
    WRAPUP_IN_PROGRESS_TTL_MS,
    type WrapupInProgressState,
} from "./storage-meta.js";
export { bumpSessionFactsVersion } from "./storage-meta-shared.js";
export {
    addNote,
    type ConditionCompileStatus,
    type DismissNoteOutcome,
    type DismissNoteResult,
    deleteNote,
    dismissNote,
    dismissNotes,
    getNoteByIdInScope,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteMutationScope,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    type UpdateNoteOptions,
    updateNote,
} from "./storage-notes.js";
export {
    clearPendingOps,
    getPendingOps,
    getPendingOpsCount,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops.js";
export * from "./storage-primers.js";
export {
    bumpProjectMemoryEpoch,
    bumpProjectUserProfileVersion,
    deleteProjectState,
    ensureProjectState,
    GLOBAL_USER_PROFILE_PROJECT_PATH,
    getProjectState,
    type ProjectStateRow,
    setProjectState,
} from "./storage-project-state.js";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source.js";
export {
    getSubagentInvocations,
    getSubagentTotalsBySubagent,
    recordSubagentInvocation,
    type SubagentInvocationInput,
    type SubagentInvocationRow,
    type SubagentKind,
    type SubagentTotals,
} from "./storage-subagent-invocations.js";
export {
    type ActiveTagTokenAggregate,
    AGE_RECLAIM_MIN_TOKENS,
    type AgeReclaimToolTag,
    adoptFallbackTagMessageId,
    adoptPiFallbackMessageTag,
    adoptPiFallbackToolOwnerTag,
    deleteTagsByMessageId,
    deriveTagLoadFloor,
    findAdoptableFallbackTags,
    findPiFallbackToolOwnerTags,
    getActiveTagsBySession,
    getActiveTagTokenAggregate,
    getActiveTagTokenTotalsByMessage,
    getActiveToolTagsForAgeReclaim,
    getAllStatusTagTokenTotalsFlat,
    getDroppedTagsByNumbers,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getMinMessageTagNumberForRawId,
    getOldestActiveUnprotectedToolTags,
    getPersistedToolTagAccounting,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTagsForPendingOperations,
    getTopNBySize,
    getTriggerTagTokenUpperBound,
    hasPiFallbackMessageTags,
    hasPiFallbackToolOwnerTags,
    insertTag,
    type MessageTokenTotal,
    markTagsCompactedByMessageIds,
    type ToolReclaimHintTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags.js";
export {
    clearV22BackfillFailures,
    deleteV22BackfillFailure,
    getV22BackfillFailure,
    listV22BackfillFailures,
    recordV22BackfillFailure,
    type V22BackfillErrorClass,
    type V22BackfillFailureRow,
} from "./storage-v22-backfill-failures.js";
export {
    bumpEpochsForWorkspaceMemberSet,
    bumpEpochsForWorkspaceMembers,
    computeWorkspaceEpochFingerprint,
    type ExpandedWorkspaceIdentitySet,
    expandWorkspaceIdentitySet,
    expandWorkspaceIdentitySetWithAliases,
    resolveStoredPathWorkspaceIdentity,
    resolveWorkspaceIdentitySet,
    sourceNameForMemory,
    storedPathBelongsToWorkspace,
    type WorkspaceIdentitySet,
} from "./workspaces.js";
